#!/usr/bin/env python3
"""Generate a cute 20x20 pixel-art puppy for the info-panel mascot.

Emits firmware/src/dog_animations.h defining dog_anims[] / DOG_ANIM_COUNT /
dog_palette using the shared pet_anim_def_t (pet_sprite.h). Draw with
primitives (precise) rather than hand-typed rows.
"""
import os

G = 20
PAL = [
    0x0000,  # 0 bg
    0xE52B,  # 1 body golden
    0x8AC5,  # 2 ear dark brown
    0xF717,  # 3 muzzle/belly cream
    0x28C2,  # 4 eye
    0x20A2,  # 5 nose / open mouth
    0xF36F,  # 6 tongue pink
    0xD1C5,  # 7 collar red
    0xFFFF,  # 8 white highlight
    0x59C3,  # 9 outline
]

def blank():
    return [[0] * G for _ in range(G)]

def px(g, x, y, v):
    if 0 <= x < G and 0 <= y < G:
        g[y][x] = v

def rect(g, x0, y0, x1, y1, v):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            px(g, x, y, v)

def base(tail_up=False, eyes="open", tongue=False, mouth="closed", dy=0):
    g = blank()
    rect(g, 2, 4, 4, 11, 2)                  # ears
    rect(g, 15, 4, 17, 11, 2)
    px(g, 2, 4, 0); px(g, 17, 4, 0)
    px(g, 2, 11, 0); px(g, 17, 11, 0)
    rect(g, 5, 3, 14, 12, 1)                 # head
    px(g, 5, 3, 0); px(g, 14, 3, 0)
    rect(g, 6, 12, 13, 17, 1)                # body
    px(g, 6, 17, 0); px(g, 13, 17, 0)
    if tail_up:                              # tail
        rect(g, 14, 11, 16, 12, 1); px(g, 16, 10, 1)
    else:
        rect(g, 14, 13, 16, 14, 1); px(g, 16, 15, 1)
    rect(g, 6, 12, 13, 12, 7)                # collar
    rect(g, 8, 14, 11, 16, 3)                # belly
    rect(g, 6, 16, 8, 18, 3)                 # paws
    rect(g, 11, 16, 13, 18, 3)
    rect(g, 7, 9, 12, 11, 3)                 # muzzle
    if eyes == "open":
        rect(g, 6, 6, 7, 8, 4); rect(g, 12, 6, 13, 8, 4)
        px(g, 6, 6, 8); px(g, 12, 6, 8)
    elif eyes == "closed":
        rect(g, 6, 7, 8, 7, 9); rect(g, 11, 7, 13, 7, 9)
    elif eyes == "happy":
        px(g, 6, 8, 9); px(g, 7, 7, 9); px(g, 8, 8, 9)
        px(g, 11, 8, 9); px(g, 12, 7, 9); px(g, 13, 8, 9)
    elif eyes == "angry":                    # slanted brows -> \  /
        px(g, 6, 6, 9); px(g, 7, 7, 4); px(g, 8, 8, 4)
        px(g, 13, 6, 9); px(g, 12, 7, 4); px(g, 11, 8, 4)
    rect(g, 9, 9, 10, 10, 5)                 # nose
    if mouth == "open":
        rect(g, 8, 11, 11, 13, 5)            # barking open mouth
        px(g, 9, 12, 6); px(g, 10, 12, 6)    # bit of tongue
    if tongue:
        rect(g, 9, 11, 10, 13, 6)
    if dy:
        s = blank()
        for y in range(G):
            if 0 <= y + dy < G:
                s[y + dy] = list(g[y])
        g = s
    return g

ANIMS = {
    "idle":  [(base(), 900), (base(dy=1), 900)],
    "blink": [(base(), 1600), (base(eyes="closed"), 140), (base(), 400),
              (base(eyes="closed"), 140)],
    "wag":   [(base(tail_up=True), 220), (base(tail_up=False), 220)],
    "happy": [(base(eyes="happy", tongue=True, tail_up=True), 240),
              (base(eyes="happy", tongue=True, tail_up=False), 240)],
    "bark":  [(base(eyes="angry", mouth="open", tail_up=True), 170),
              (base(eyes="angry", mouth="closed", tail_up=True), 170)],
    "sleep": [(base(eyes="closed", dy=1), 1200),
              (base(eyes="closed", dy=2), 1200)],
}

def flat(g):
    return ",".join(str(g[y][x]) for y in range(G) for x in range(G))

def main():
    root = os.path.join(os.path.dirname(__file__), "..", "firmware", "src")
    out = os.path.join(root, "dog_animations.h")
    L = ["// Generated by tools/gen_dog.py — cute puppy for the info panel.",
         "#pragma once", '#include "pet_sprite.h"', ""]
    L.append("static const uint16_t dog_palette[10] = {" +
             ",".join("0x%04X" % c for c in PAL) + "};")
    L.append("")
    for name, frames in ANIMS.items():
        L.append("static const uint8_t dog_%s_frames[%d][400] = {" % (name, len(frames)))
        for g, _ in frames:
            L.append("    {" + flat(g) + "},")
        L.append("};")
        L.append("static const uint16_t dog_%s_holds[%d] = {%s};" %
                 (name, len(frames), ",".join(str(h) for _, h in frames)))
        L.append("")
    L.append("static const pet_anim_def_t dog_anims[] = {")
    for name, frames in ANIMS.items():
        L.append('    {"%s", %d, dog_palette, dog_%s_frames, dog_%s_holds},' %
                 (name, len(frames), name, name))
    L.append("};")
    L.append("#define DOG_ANIM_COUNT %d" % len(ANIMS))
    L.append("")
    with open(out, "w") as f:
        f.write("\n".join(L))
    print("wrote", out, "(%d animations)" % len(ANIMS))

if __name__ == "__main__":
    main()
