#!/usr/bin/env python3
"""Generate a cute 20x20 pixel-art cat companion for the info panel.

Emits firmware/src/cat_animations.h defining cat_anims[] / CAT_ANIM_COUNT /
cat_palette using the shared pet_anim_def_t (pet_sprite.h).
"""
import os

G = 20
PAL = [
    0x0000,  # 0 bg
    0xC639,  # 1 body light grey
    0x6BAF,  # 2 ear/whisker dark grey
    0xF79E,  # 3 muzzle/chest white
    0x460B,  # 4 eye green
    0xE454,  # 5 nose pink
    0xF06F,  # 6 mouth pink
    0x3BDA,  # 7 collar blue
    0xFFFF,  # 8 white highlight / fang
    0x39E8,  # 9 outline
]

def blank():
    return [[0] * G for _ in range(G)]

def px(g, x, y, v):
    if 0 <= x < G and 0 <= y < G:
        g[y][x] = v

def rect(g, x0, y0, x1, y1, v):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            px(g, x, y, v)

def base(eyes="open", mouth="closed", tail="curl", dy=0):
    g = blank()
    # Pointed ears.
    px(g, 5, 2, 2); rect(g, 4, 3, 6, 3, 2); rect(g, 4, 4, 7, 4, 2); px(g, 5, 4, 5)
    px(g, 14, 2, 2); rect(g, 13, 3, 15, 3, 2); rect(g, 12, 4, 15, 4, 2); px(g, 14, 4, 5)
    # Head.
    rect(g, 4, 4, 15, 12, 1)
    px(g, 4, 4, 0); px(g, 15, 4, 0)
    # Body.
    rect(g, 5, 12, 14, 17, 1)
    px(g, 5, 17, 0); px(g, 14, 17, 0)
    # Tail.
    if tail == "curl":
        rect(g, 15, 13, 16, 16, 1); px(g, 16, 12, 1)
    else:  # up
        rect(g, 15, 9, 16, 12, 1); px(g, 16, 8, 1)
    # Collar + chest + paws.
    rect(g, 5, 12, 14, 12, 7)
    rect(g, 8, 13, 11, 16, 3)
    rect(g, 6, 16, 8, 18, 3); rect(g, 11, 16, 13, 18, 3)
    # Muzzle + whiskers.
    rect(g, 7, 9, 12, 12, 3)
    px(g, 3, 10, 2); px(g, 2, 11, 2); px(g, 16, 10, 2); px(g, 17, 11, 2)
    # Eyes.
    if eyes == "open":
        rect(g, 6, 7, 7, 8, 4); rect(g, 12, 7, 13, 8, 4)
        px(g, 6, 7, 8); px(g, 12, 7, 8)
    elif eyes == "closed":
        rect(g, 6, 7, 8, 7, 9); rect(g, 11, 7, 13, 7, 9)
    elif eyes == "happy":
        px(g, 6, 8, 9); px(g, 7, 7, 9); px(g, 8, 8, 9)
        px(g, 11, 8, 9); px(g, 12, 7, 9); px(g, 13, 8, 9)
    elif eyes == "wide":
        rect(g, 6, 6, 8, 8, 4); rect(g, 11, 6, 13, 8, 4)
        px(g, 6, 6, 8); px(g, 11, 6, 8)
    elif eyes == "angry":
        px(g, 6, 6, 9); px(g, 7, 7, 4); px(g, 8, 8, 4)
        px(g, 13, 6, 9); px(g, 12, 7, 4); px(g, 11, 8, 4)
    # Nose.
    px(g, 9, 9, 5); px(g, 10, 9, 5)
    # Hissing open mouth with fangs.
    if mouth == "open":
        rect(g, 8, 10, 11, 12, 6); px(g, 8, 10, 8); px(g, 11, 10, 8)
    if dy:
        s = blank()
        for y in range(G):
            if 0 <= y + dy < G:
                s[y + dy] = list(g[y])
        g = s
    return g

ANIMS = {
    "idle":  [(base(), 1500), (base(eyes="closed"), 150), (base(), 600),
              (base(dy=1), 900)],
    "happy": [(base(eyes="happy", tail="up"), 260),
              (base(eyes="happy", tail="curl"), 260)],
    "hiss":  [(base(eyes="angry", mouth="open", tail="up"), 160),
              (base(eyes="wide", mouth="open", tail="up"), 160)],
    "sleep": [(base(eyes="closed", dy=1), 1200),
              (base(eyes="closed", dy=2), 1200)],
    "alert": [(base(eyes="wide", tail="up"), 380),
              (base(eyes="wide", tail="up", dy=1), 380)],
}

def flat(g):
    return ",".join(str(g[y][x]) for y in range(G) for x in range(G))

def main():
    root = os.path.join(os.path.dirname(__file__), "..", "firmware", "src")
    out = os.path.join(root, "cat_animations.h")
    L = ["// Generated by tools/gen_cat.py — cute cat for the info panel.",
         "#pragma once", '#include "pet_sprite.h"', ""]
    L.append("static const uint16_t cat_palette[10] = {" +
             ",".join("0x%04X" % c for c in PAL) + "};")
    L.append("")
    for name, frames in ANIMS.items():
        L.append("static const uint8_t cat_%s_frames[%d][400] = {" % (name, len(frames)))
        for g, _ in frames:
            L.append("    {" + flat(g) + "},")
        L.append("};")
        L.append("static const uint16_t cat_%s_holds[%d] = {%s};" %
                 (name, len(frames), ",".join(str(h) for _, h in frames)))
        L.append("")
    L.append("static const pet_anim_def_t cat_anims[] = {")
    for name, frames in ANIMS.items():
        L.append('    {"%s", %d, cat_palette, cat_%s_frames, cat_%s_holds},' %
                 (name, len(frames), name, name))
    L.append("};")
    L.append("#define CAT_ANIM_COUNT %d" % len(ANIMS))
    L.append("")
    with open(out, "w") as f:
        f.write("\n".join(L))
    print("wrote", out, "(%d animations)" % len(ANIMS))

if __name__ == "__main__":
    main()
